In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [3]:
df = pd.read_excel(r"C:\Users\ACER\Desktop\Data Analitika\Korelyasiya.xlsx")
df.head(5)

   Evin Sahəsi (m2)  Mərkəzdən Məsafə (km)  Qiymət (min AZN)
0                50                      2               120
1                65                      5               110
2                80                      1               180
3               100                     10               150
4                40                     15                70

In [5]:
matris = df.corr()
matris

,Evin Sahəsi (m2),Mərkəzdən Məsafə (km),Qiymət (min AZN)
Evin Sahəsi (m2),1.000000,-0.450944,0.978822
Mərkəzdən Məsafə (km),-0.450944,1.000000,-0.560923
Qiymət (min AZN),0.978822,-0.560923,1.000000

In [6]:
korelyasiya = df['Evin Sahəsi (m2)'].corr(df['Qiymət (min AZN)'])
korelyasiya

np.float64(0.9788215479488876)