In [1]:
import pandas as pd
import numpy as np

In [33]:
# 1. Excel faylını oxuyuruq
df = pd.read_excel(r'C:\Users\ACER\Desktop\Data statistika 1.xlsx')
df

       Ad       Şöbə  Maas
0     Ali         IT  1200
1    Vəli         HR  1500
2   Həsən         IT  1800
3   Gülər    Maliyyə  1300
4   Nigar  Marketinq  1700
5   Orxan         IT  2100
6  Səbinə         HR  1450

In [7]:
# Pandas ilə Ortalama (Mean) hesablamaq
# df['Maas'] - sadəcə maaş sütununu götürür
pandas_mean = df['Maas'].mean()
print(pandas_mean)
print(f"Pandas ilə hesablanan Orta Maaş: {pandas_mean:.2f} AZN")

1578.5714285714287
Pandas ilə hesablanan Orta Maaş: 1578.57 AZN

In [9]:
# NumPy ilə Ortalama hesablamaq
# Eyni nəticəni verir, riyazi yanaşmadır
numpy_mean = np.mean(df['Maas'])
print(numpy_mean)
print(f"Numpy ile hesablanan orta maas: {numpy_mean:.2f} AZN")

1578.5714285714287
Numpy ile hesablanan orta maas: 1578.57 AZN

In [10]:
# bes şöbeler üçün ayrı-ayrı ortalama tapmaq istəsək onda necə edirik? 
# yol 1 -  menfi terefi odurki şirketde şöbe sayı çox olarsa çox setir yazmaq lazım gelecek

# 1. Sadəcə IT şöbəsini seçirik
it_iscileri = df[df['Şöbə'] == 'IT']
it_ortalama = it_iscileri['Maas'].mean()

# 2. Sadəcə HR şöbəsini seçirik
hr_iscileri = df[df['Şöbə'] == 'HR']
hr_ortalama = hr_iscileri['Maas'].mean()

print(f"IT Şöbəsinin Ortalaması: {it_ortalama}")
print(f"HR Şöbəsinin Ortalaması: {hr_ortalama}")

IT Şöbəsinin Ortalaması: 1700.0
HR Şöbəsinin Ortalaması: 1475.0

In [11]:
# 2 ci yol Pivot Table mentiqidir 
# pivot_table istifadə edərək
# values = Hesablayacağımız sütun (Maaş)
# index = Sətirlərdə nə olsun? (Şöbə)
# aggfunc = Hansı funksiya? ('mean' - ortalama)

pivot_netice = df.pivot_table(values='Maas', index='Şöbə', aggfunc='mean')

print("--- Pivot Table ilə Nəticə ---")
print(pivot_netice)

--- Pivot Table ilə Nəticə ---
             Maas
Şöbə
HR         1475.0
IT         1700.0
Maliyyə    1300.0
Marketinq  1700.0

In [13]:
# GroupBy mentiqi 
# Şöbələr üzrə qruplaşdırıb ortalamanı tapırıq
# Məntiq: df.groupby('HANSINA_GÖRƏ_QRUPLAŞDIRIM')['HANSI_SÜTUNU_HESABLAYIM'].mean()

sobe_ortalamasi = df.groupby('Şöbə')['Maas'].mean()
sobe_ortalamasi

Şöbə
HR           1475.0
IT           1700.0
Maliyyə      1300.0
Marketinq    1700.0
Name: Maas, dtype: float64

In [14]:
# 1. Pandas ilə Median
# Diqqət: Pandas arxada özü sıralayır, bizim "sort" etməyimizə ehtiyac qalmır.
median_pandas = df['Maas'].median()
median_pandas

np.float64(1500.0)

In [15]:
# NumPy ilə Median
median_numpy = np.median(df['Maas'])
median_numpy

np.float64(1500.0)

In [16]:
sobe_modasi = df['Şöbə'].mode()
sobe_modasi

0    IT
Name: Şöbə, dtype: object

In [17]:
# 1. Excel faylını oxuyuruq
df = pd.read_excel(r'C:\Users\ACER\Desktop\Data statistika 1.xlsx',sheet_name="stdev")
df

   ID Tələbə        Fənn  Bal
0   1  Aysel  Riyaziyyat   85
1   2  Samir  Riyaziyyat   72
2   3  Leyla  Riyaziyyat   90
3   4  Kənan  Riyaziyyat   45
4   5  Murad  Riyaziyyat   60
5   6  Günel  Riyaziyyat   88
6   7  Turan  Riyaziyyat   95
7   8  Fidan  Riyaziyyat   55
8   9  Orxan  Riyaziyyat   78
9  10  Elvin  Riyaziyyat   82

In [22]:
# Əvvəlcə 'Bal' sütununu df-dən çıxarıb 'ballar' adında bir dəyişənə qoyuruq
ballar = df['Bal'] 

# İndi artıq 'ballar' dəyişənini istifadə edə bilərik
ortalama = ballar.mean()
variance = ballar.var()
std_dev = ballar.std()

print(f"Ortalama: {ortalama}")
print(f"varyans: {variance}")
print(f"Standart Kənarlaşma: {std_dev}")

Ortalama: 75.0
varyans: 276.22222222222223
Standart Kənarlaşma: 16.619934483090546

In [29]:
# 1. Excel faylını oxuyuruq
df = pd.read_excel(r'C:\Users\ACER\Desktop\Data statistika 1.xlsx',sheet_name="X")
df

     İl  Gelir
0  2019    4.0
1  2020   14.3
2  2021   19.0
3  2022  -14.7
4  2023  -26.5
5  2024   37.2
6  2025   23.8

In [30]:
import pandas as pd
gelir = df['Gelir']

ortalama_gelir = gelir.mean()
standart_kenarlasma = gelir.std()

print(ortalama_gelir)
print(standart_kenarlasma)

8.157142857142857
22.302231363913428

In [31]:
# 1. Excel faylını oxuyuruq
df2 = pd.read_excel(r'C:\Users\ACER\Desktop\Data statistika 1.xlsx',sheet_name="Y")
df2

     İl  Gelir
0  2019    6.5
1  2020    4.4
2  2021    3.8
3  2022    6.9
4  2023    8.0
5  2024    5.8
6  2025    5.1

In [32]:
gelir = df2['Gelir']

ortalama_gelir2 = gelir.mean()
standart_kenarlasma2 = gelir.std()

print(ortalama_gelir2)
print(standart_kenarlasma2)

5.785714285714286
1.471312986676154